name: 测试一下
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 打印当前目录下的文件
        run: |
          pwd
          ls -la
